### ISSUE TITLE
Research map image resources (free licensed) of Portland

### ISSUE THREAD

**Issue by DrewStock** [4-the-rodentz/App#7]

**Comment by DrewStock** [comment]
I’ve been playing around with static images of Google maps and I’ve created an example .html file that has map quadrants of Portland (Downtown, SouthEast, NorthEast & North). The example file is named static_map_image_example.html and is in the ‘additional documents’ folder of the project repository.

I generated the URLs for the images using a handy app called Google Static Map Maker: http://staticmapmaker.com/google/ 

There’s more info about the Google Static Maps API at:
https://developers.google.com/maps/documentation/static-maps/ 

Here's a screenshot of the example file:
<img width="1280" alt="screenshot 2016-08-10 14 10 42" src="https://cloud.githubusercontent.com/assets/18359492/17571932/258a9abc-5f07-11e6-91c9-6c08fcfce6f6.png">

**Comment by jonwalz** [comment]
This looks like a great option! I feel like we would have to figure out how to make the placement on the page look aesthetically pleasing with that gap at the top. But at this point, this looks very promising!

**Comment by DrewStock** [comment]
After considering the research by @jonwalz of using Google Maps for capturing location data from user clicks, it appears that we can discard the idea of using static map images for this purpose.
